name: Dev2

on: 
   push:
     branches : 
       - dev2
   pull_request:
     branches : 
       - dev2

jobs:
  MacOS-Chez:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: use Setup-Scheme
      uses: guenchi/setup-scheme@dev2
      with:
        implementation: chez

    - run: chez --version
  
  MacOS-Gambit:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: use Setup-Scheme
      uses: guenchi/setup-scheme@dev2
      with:
        implementation: gambit

    - run: gsi -v

  MacOS-Grebil:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: use Setup-Scheme
      uses: guenchi/setup-scheme@dev2
      with:
        implementation: grebil

    - run: |
            export PATH=/usr/local/opt/gambit-scheme/current/bin:/usr/local/opt/gerbil-scheme/libexec/bin:$PATH
            export GERBIL_HOME=/usr/local/opt/gerbil-scheme/libexec
            gxi

  MacOS-MIT:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: use Setup-Scheme
      uses: guenchi/setup-scheme@dev2
      with:
        implementation: mit

    - run: scheme --version

  Linux-Chez:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: use Setup-Scheme
      uses: guenchi/setup-scheme@dev2
      with:
        implementation: chez

    - run: scheme --version

  Linux-Gambit:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: use Setup-Scheme
      uses: guenchi/setup-scheme@dev2
      with:
        implementation: gambit

    - run: gsi -v

  Linux-MIT:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: use Setup-Scheme
      uses: guenchi/setup-scheme@dev2
      with:
        implementation: mit

    - run: scheme --version


