name: Dev2

on: 
   push:
     branches : 
       - dev2
   pull_request:
     branches : 
       - dev2

jobs:
  MacOS-Chez:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: use Setup-Scheme
      uses: guenchi/setup-scheme@dev2
      with:
        implementation: chez

    - run: chez --version
  
  MacOS-MIT:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: use Setup-Scheme
      uses: guenchi/setup-scheme@dev2
      with:
        implementation: mit

    - run: scheme --version

  Linux-Chez:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: use Setup-Scheme
      uses: guenchi/setup-scheme@dev2
      with:
        implementation: chez

    - run: scheme --version

  Linux-MIT:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: use Setup-Scheme
      uses: guenchi/setup-scheme@dev2
      with:
        implementation: mit

    - run: scheme --version


